#!/usr/bin/env bash
# Puts PID into a file and processes it

echo "$$" >> myscript.pid && sudo mv myscript.pid /var/run/myscript.pid

cleanup()
{
	sudo rm -f /var/run/myscript.pid
}

trap "echo I hate the kill command" && "echo cleanup" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "echo cleanup" SIGQUIT

while true
do
	echo To infinity and beyond
	sleep 2
done
