#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely, with sleep 2 and a quote upoon start

trap "echo I am invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

